#!/bin/sh
set -e
case "$1" in remove|upgrade|deconfigure)
  systemctl disable --now nls-router.service >/dev/null 2>&1 || true
  systemctl disable --now nls-ca.service >/dev/null 2>&1 || true
  ;;
esac
exit 0